name: cookiecutter
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
      - main
    paths:
      - cookiecutter-wrapper-v1/__tests__/cookiecutter-template/**
      - ./__tests__/matrix_example.yaml

jobs:
  cookiecutter-process-templates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: cookiecutter-wrapper
        uses: stemdo/actions/cookiecutter-wrapper-v1@main
        with:
          template-folder: "cookiecutter-wrapper-v1/__tests__/cookiecutter-template/template"
          matrix-file: "cookiecutter-wrapper-v1/__tests__/matrix.example.yaml"
          cookiecutter-specific-file-pattern: "cookiecutter-{{ vertical }}-{{ proyecto }}.yaml"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@7380612b49221684fefa025244f2ef4008ae50ad
        with:
          branch: update-cookiecutter-templates-branch-${{ github.ref_name }}
          delete-branch: true
          commit-message: '[automated-change]: process cookiecutter templates'
          title: '[automated-change] Update cookiecutter templates in branch [${{ github.ref_name }}]'
          body: |
            Pull Request created automatically with the workflow run [${{ github.workflow }}](${{ github.event.repository.svn_url }}/actions/runs/${{ github.run_id }}).
            More information about this process: [README.md](https://github.com/backstage-tutorial/testing-templates/blob/main/cookiecutter-terraform/README.md)
            *Please, do not manually modify the body of this PR as it can be automatically overwritten, use the comment section instead.*
